resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/18/16.yaml

compiler: ghc-9.0.2

setup-info:
  ghc:
    linux64-tinfo6:
      9.0.2:
        url: "https://downloads.haskell.org/ghc/9.0.2/ghc-9.0.2a-x86_64-fedora27-linux.tar.xz"

packages:
- .

extra-deps:
- git: https://github.com/OctopiChalmers/BinderAnn
  commit: 8f082b23ebd4e79e86e934f41ddfcba59652fadd
